#!/bin/bash

: ${TRINIT:=/etc/trinit}

TIMEOUT=5

if [ $# -ne 0 ]
then
  if [ -d $TRINIT/$1 ]
  then
    cd $TRINIT/$1
  else
     echo "$1 not found under $TRINIT"
     exit 1
  fi
fi

ME=${PWD/$TRINIT\//}
T=/tmp/trinit/`basename $PWD`

while ! mkdir $T/lock 2>/dev/null; do sleep 1; done

if [ ! -f $T/isup ]
then
  echo "$ME isn't up"
  rmdir $T/lock
  exit 1
fi

echo "Downing $ME"

for D in `find -L * -mindepth 0 -maxdepth 0 -type d 2> /dev/null`
do
  ( cd $D; down ) &
done

wait

if [ ! -x stop ] || timeout $TIMEOUT ./stop
then
  rm -rf $T/isup
else
  echo "Failed to stop $ME"
  rmdir $T/lock
  exit 1
fi

rmdir $T/lock

