#!/bin/bash

: ${TRINIT:=/etc/trinit}
echo "TRINIT=$TRINIT"

TIMEOUT=20

if [ $# -ne 0 ]
then
  if [ -d $TRINIT/$1 ]
  then
    cd $TRINIT/$1
  else
     echo "$1 not found under $TRINIT"
     exit 1
  fi
fi

ME=${PWD/$TRINIT\//}
T=/tmp/trinit/`basename $PWD`

# if ! checkdeps; then exit 1; fi

mkdir -p $T

while ! mkdir $T/lock 2>/dev/null; do sleep 1; done

echo "Locked $T"

if [ -f $T/isup ]
then
  echo "$ME is already up"
  rmdir $T/lock
  echo "Unlocked $T"
  exit 0
fi

if [ -f deps ]
then
  for X in `cat deps`
  do
    if ! isup $X
    then
      echo "Postponing $ME"
      rmdir $T/lock
      echo "Unlocked $T"
      exit 2
    fi
  done
fi

echo "Upping $ME"

if [ ! -x start ] || timeout $TIMEOUT ./start
then
  touch $T/isup
else
  echo "Failed to start $ME"
  rmdir $T/lock
  echo "Unlocked $T"
  exit 1
fi

for D in `find -L * -mindepth 0 -maxdepth 0 -type d 2>/dev/null`
do
  echo "Doing $D"
  ( cd $D; up ) &
done

wait

rmdir $T/lock
echo "Unlocked $T"
  
